### PR TITLE
Stub for resources page and better handling of top navigation

### PR DESCRIPTION
**Pull request by ergo**

### CODE REVIEW

**Comment by blaflamme** [comment]
I can't run it here in debug mode or build a dist version, assets are missing so I just see a broken version. I'll take a look tomorrow when I'm back home but a few comments:

- use vars for colors and padding/margin for main blocks, no hard-coding
- only home has a top hero section, others just topnav and header/title section

**Comment by stevepiercy** [comment]
I've created a new branch in PR #27 which is a variation on Ergo's work here. It uses vars in the SCSS, and implements `nav#nav` in a way that satisfies my usability and accessibility concerns from #20.

**Comment by blaflamme** [comment]
ok I've updated the project webpack configs and packages, you shoud re-run npm install to make it work properly. I also merged my update and latest @ergo changes back in ergo-master branch to test it out.

Quick notes... to me the navbar doesn't satisfy my initial design and purpose I have for the home page, I still think it doesn't need to be the first thing you see on the front page of a marketing oriented micro-site. The navbar transparency works now, but as soon as we will change how we use the hero section we'll have to adapt the styling. The compromise I see to accommodate the fact that «it needs» to be visible on initial page load is to move it below the hero section and stick it when it reaches the top. Remember it's only for the home page.

I'm happy to see some content being added :)

I think we should group content by type, ie: docs, tuts, ..., and provide them a block with one icon for the group. Also having full width block with so less text makes it not well balanced, we should probably use a two columns block similar to the home page. Each item title (in red) should probably use something like an H4 and have the subtitle under, that would make items headers easier to read and find what could be interesting. Descriptions are not first-class citizen, they complement blocks where you stop because of an interest.

This is not a documentation site, it's a marketing site and each page would probably need its own design specifics based on content; quantity, number of items, titles, ... If the page looks like a project documentation page «à la sphinx», we did it wrong.

For CSS, don't add specifics to generic tags like body or any other default, style components and their parents.

**Comment by blaflamme** [comment]
@stevepiercy @ergo ok here's my take on the navbar based on your work guys.

https://github.com/Pylons/tpc/tree/topnav-wip

**Comment by pauleveritt** [comment]
Agreed on this not being a documentation site, although I do hope it comes to provide a better ToC of the docs than the current docs pages.

**Comment by pauleveritt** [comment]
To zoom back out, the world of Pyramid badly, badly needs trypyramid.com. Whether we have a hidden navbar or not is very far down the list. :)

I propose we meta this issue. Let’s keep it in the tracker but ignore it for now. We can look at some other framework sites and see who does/doesn’t hide nav for their marketing-oriented sites. We can also later poll some users and see what they think.

For now, let’s focus on launch. Get some tickets entered that identify everything needed to launch this thing. Organize a milestone or two. Get it out the door. Perhaps schedule an (online) sprint.

—Paul

**Comment by stevepiercy** [comment]
> Get some tickets entered that identify everything needed to launch this thing. Organize a milestone or two.

You mean something like this? :grin: 
https://github.com/Pylons/tpc/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.2

**Comment by pauleveritt** [comment]
Yes, great! Though several of those look like things that could easily be post-launch. And we probably have some activities that aren’t entered, but needed.

—Paul

**Comment by blaflamme** [comment]
@pauleveritt my work on it is almost done, so not a big deal.

**Comment by pauleveritt** [comment]
Are you part of any work to get it deployed to the box?

—Paul

**Comment by blaflamme** [comment]
@pauleveritt yes it's still done manually

**Comment by stevepiercy** [comment]
http://localhost:8080/
* YES! This solves the concerns I have about in/visible navigation.
* I like the smaller onhover rectangles in the nav.
* I like the animation/transition and contrasting color on scroll. High contrast makes users with visual impairments happier.
* I fiddled with `border-radius: 10px;` in the onhover state to see how rounded corners would look. That's only a comment, not suggestion or request, and let @blaflamme be the judge.
google chrome005

http://localhost:8080/resources.html
* Nav works for me.
* Agree we need to dress up the content on Resources. I'll throw some effort into that on this branch next.

**Comment by stevepiercy** [comment]
I put my changes to Resources in a new PR #28 because I couldn't figure out how to push my commits to this PR.

**Comment by blaflamme** [comment]
@stevepiercy +1 on rounded corner, but keep it thin... 5px radius?

**Comment by blaflamme** [comment]
@stevepiercy work from topnav branch, it already contains all changes

**Comment by stevepiercy** [comment]
@blaflamme I thought I did that, but I must have missed a step. I checked out topnav-wip as a new local branch, made edits, made commit, and pushed, but it didn't show up here. Instead it showed up as a new PR. :confused:

**Comment by blaflamme** [comment]
@stevepiercy you can merge the PR to topnav-wip branch. If you have topnav-wip pulled locally you can do something like:

$ git checkout topnav-wip && git merge ${remote}/${branch}

**Comment by stevepiercy** [comment]
```
git checkout topnav-wip && git merge ${remote}/${branch}
Already on 'topnav-wip'
Your branch is up-to-date with 'origin/topnav-wip'.
merge: / - not something we can merge
```

**Comment by blaflamme** [comment]
@stevepiercy I don't know what you did but your PR got merged to topnav-wip

**Comment by stevepiercy** [comment]
@blaflamme Ha! Me neither. Originally I pushed to upstream (Pylons) instead of origin (my fork). Within the last few minutes, I closed that other PR, then pushed to origin (my fork) instead of upstream (Pylons).

**Comment by stevepiercy** [comment]
@blaflamme I just pushed another change to both upstream and remote on the branch topnav-wip for the rounded corners. Do I need to do anything else at this time, or do you got it from here?

**Comment by blaflamme** [comment]
@stevepiercy LGTM

**Pull request merged**
